### ISSUE TITLE
2021-09-23: Logos not loading

### ISSUE THREAD

**Issue by thodel** [critique-digitale/critique-digitale.ch#3]
**Describe the bug**
The logos are not loaded properly, when the german version is loaded first

**To Reproduce**
go directly to https://critique-digitale.ch/de/ (maybe empty cache).

Scroll down to the bottom
See error

**Expected behavior**
Display correct logos

**Screenshots**
See screenshot:
<img width="1223" alt="screenshot_missing-logos" src="https://user-images.githubusercontent.com/18015683/134576529-d7b29229-d175-4d17-88f5-2da0c1a418fe.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox
- Version: 92.0

**Comment by maehr** [comment]
I will fix this Issue asap, latest next Tuesday.
