### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by janosh** [critique-digitale/critique-digitale.ch#5]
[Looks like the site is down](https://github.com/janosh/awesome-svelte-kit/runs/5678114493?check_suite_focus=true#step:4:190).

**Comment by maehr** [comment]
fixed with https://github.com/critique-digitale/critique-digitale.ch/commit/2cd169b621e496f6cca01a31c24ee9a8671cf443
Documentation: We switched to the adapter for Cloudflare Pages and installed a downtime monitor. In the long run we should probably switch to GitHub Pages.
